### ISSUE TITLE
Add configuration files

### ISSUE THREAD

**Issue by graillus** [graillus/gcrgc#15]
Configuration files could simplify complex cleanup workflows, for instance when there are lots of exclusion rules to provide, or simply to allow multiple different configurations to be saved into files.

Example usage:
```bash
gcrgc --config=path/to/config.yaml
```

I'm thinking of the following file structure (matching the command-line flags for simpler utilisation and implementation):
config.yaml:
```yaml
registry: gcr.io/project-id
retention-period: 30d
exclude-repositories:
  - nginx
exclude-semver-tags: true
exclude-tags:
  - latest
  - dev-master
```
